%General Mission Analysis Tool(GMAT) Script
%Created: 2026-01-07 10:36:08


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft Shuttle;
Shuttle.DateFormat = UTCGregorian;
Shuttle.Epoch = '24 Dec 1998 00:00:00.000';
Shuttle.CoordinateSystem = EarthMJ2000Eq;
Shuttle.DisplayStateType = Keplerian;
Shuttle.SMA = 6563.369800000003;
Shuttle.ECC = 0.004806000000000446;
Shuttle.INC = 45;
Shuttle.RAAN = 95.262775;
Shuttle.AOP = 50.3750779999983;
Shuttle.TA = 8.537736462515939e-07;
Shuttle.DryMass = 850;
Shuttle.Cd = 2.2;
Shuttle.Cr = 1.8;
Shuttle.DragArea = 15;
Shuttle.SRPArea = 1;
Shuttle.SPADDragScaleFactor = 1;
Shuttle.SPADSRPScaleFactor = 1;
Shuttle.AtmosDensityScaleFactor = 1;
Shuttle.ExtendedMassPropertiesModel = 'None';
Shuttle.NAIFId = -10000001;
Shuttle.NAIFIdReferenceFrame = -9000001;
Shuttle.OrbitColor = Red;
Shuttle.TargetColor = Teal;
Shuttle.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
Shuttle.CdSigma = 1e+70;
Shuttle.CrSigma = 1e+70;
Shuttle.Id = 'SatId';
Shuttle.Attitude = CoordinateSystemFixed;
Shuttle.SPADSRPInterpolationMethod = Bilinear;
Shuttle.SPADSRPScaleFactorSigma = 1e+70;
Shuttle.SPADDragInterpolationMethod = Bilinear;
Shuttle.SPADDragScaleFactorSigma = 1e+70;
Shuttle.AtmosDensityScaleFactorSigma = 1e+70;
Shuttle.ModelFile = 'aura.3ds';
Shuttle.ModelOffsetX = 0;
Shuttle.ModelOffsetY = 0;
Shuttle.ModelOffsetZ = 0;
Shuttle.ModelRotationX = 0;
Shuttle.ModelRotationY = 0;
Shuttle.ModelRotationZ = 0;
Shuttle.ModelScale = 1;
Shuttle.AttitudeDisplayStateType = 'Quaternion';
Shuttle.AttitudeRateDisplayStateType = 'AngularVelocity';
Shuttle.AttitudeCoordinateSystem = EarthMJ2000Eq;
Shuttle.EulerAngleSequence = '321';

Create Spacecraft Mir;
Mir.DateFormat = UTCGregorian;
Mir.Epoch = '24 Dec 1998 03:40:53.615';
Mir.CoordinateSystem = EarthMJ2000Eq;
Mir.DisplayStateType = Keplerian;
Mir.SMA = 6727.706099999998;
Mir.ECC = 0.0007444000000001812;
Mir.INC = 51.65979999999999;
Mir.RAAN = 159.7517;
Mir.AOP = 117.6835000000176;
Mir.TA = 242.4908999999824;
Mir.DryMass = 850;
Mir.Cd = 2.2;
Mir.Cr = 1.8;
Mir.DragArea = 15;
Mir.SRPArea = 1;
Mir.SPADDragScaleFactor = 1;
Mir.SPADSRPScaleFactor = 1;
Mir.AtmosDensityScaleFactor = 1;
Mir.ExtendedMassPropertiesModel = 'None';
Mir.NAIFId = -10004001;
Mir.NAIFIdReferenceFrame = -9004001;
Mir.OrbitColor = Yellow;
Mir.TargetColor = DarkGray;
Mir.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
Mir.CdSigma = 1e+70;
Mir.CrSigma = 1e+70;
Mir.Id = 'SatId';
Mir.Attitude = CoordinateSystemFixed;
Mir.SPADSRPInterpolationMethod = Bilinear;
Mir.SPADSRPScaleFactorSigma = 1e+70;
Mir.SPADDragInterpolationMethod = Bilinear;
Mir.SPADDragScaleFactorSigma = 1e+70;
Mir.AtmosDensityScaleFactorSigma = 1e+70;
Mir.ModelFile = 'aura.3ds';
Mir.ModelOffsetX = 0;
Mir.ModelOffsetY = 0;
Mir.ModelOffsetZ = 0;
Mir.ModelRotationX = 0;
Mir.ModelRotationY = 0;
Mir.ModelRotationZ = 0;
Mir.ModelScale = 1;
Mir.AttitudeDisplayStateType = 'Quaternion';
Mir.AttitudeRateDisplayStateType = 'AngularVelocity';
Mir.AttitudeCoordinateSystem = EarthMJ2000Eq;
Mir.EulerAngleSequence = '321';

Create Spacecraft Buran;
Buran.DateFormat = TAIModJulian;
Buran.Epoch = '21545';
Buran.CoordinateSystem = EarthMJ2000Eq;
Buran.DisplayStateType = Cartesian;
Buran.X = 7100;
Buran.Y = 0;
Buran.Z = 1300;
Buran.VX = 0;
Buran.VY = 7.35;
Buran.VZ = 1;
Buran.DryMass = 850;
Buran.Cd = 2.2;
Buran.Cr = 1.8;
Buran.DragArea = 15;
Buran.SRPArea = 1;
Buran.SPADDragScaleFactor = 1;
Buran.SPADSRPScaleFactor = 1;
Buran.AtmosDensityScaleFactor = 1;
Buran.ExtendedMassPropertiesModel = 'None';
Buran.NAIFId = -10005001;
Buran.NAIFIdReferenceFrame = -9005001;
Buran.OrbitColor = Blue;
Buran.TargetColor = DimGray;
Buran.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
Buran.CdSigma = 1e+70;
Buran.CrSigma = 1e+70;
Buran.Id = 'SatId';
Buran.Attitude = CoordinateSystemFixed;
Buran.SPADSRPInterpolationMethod = Bilinear;
Buran.SPADSRPScaleFactorSigma = 1e+70;
Buran.SPADDragInterpolationMethod = Bilinear;
Buran.SPADDragScaleFactorSigma = 1e+70;
Buran.AtmosDensityScaleFactorSigma = 1e+70;
Buran.ModelFile = 'aura.3ds';
Buran.ModelOffsetX = 0;
Buran.ModelOffsetY = 0;
Buran.ModelOffsetZ = 0;
Buran.ModelRotationX = 0;
Buran.ModelRotationY = 0;
Buran.ModelRotationZ = 0;
Buran.ModelScale = 1;
Buran.AttitudeDisplayStateType = 'Quaternion';
Buran.AttitudeRateDisplayStateType = 'AngularVelocity';
Buran.AttitudeCoordinateSystem = EarthMJ2000Eq;
Buran.EulerAngleSequence = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0.002288329519450801 0 ];
DefaultOrbitView.Size = [ 0.5002288329519451 0.4504761904761905 ];
DefaultOrbitView.RelativeZOrder = 409;
DefaultOrbitView.Maximized = false;
DefaultOrbitView.Add = {Shuttle, Earth};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true ];
DefaultOrbitView.DataCollectFrequency = 1;
DefaultOrbitView.UpdatePlotFrequency = 50;
DefaultOrbitView.NumPointsToRedraw = 0;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.MaxPlotPoints = 20000;
DefaultOrbitView.ShowLabels = true;
DefaultOrbitView.ViewPointReference = Earth;
DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
DefaultOrbitView.ViewDirection = Earth;
DefaultOrbitView.ViewScaleFactor = 1;
DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.ViewUpAxis = Z;
DefaultOrbitView.EclipticPlane = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.WireFrame = Off;
DefaultOrbitView.Axes = On;
DefaultOrbitView.Grid = Off;
DefaultOrbitView.SunLine = Off;
DefaultOrbitView.UseInitialView = On;
DefaultOrbitView.StarCount = 7000;
DefaultOrbitView.EnableStars = On;
DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
DefaultGroundTrackPlot.SolverIterations = Current;
DefaultGroundTrackPlot.UpperLeft = [ 0.002288329519450801 0.4542857142857143 ];
DefaultGroundTrackPlot.Size = [ 0.5002288329519451 0.4504761904761905 ];
DefaultGroundTrackPlot.RelativeZOrder = 123;
DefaultGroundTrackPlot.Maximized = false;
DefaultGroundTrackPlot.Add = {Shuttle};
DefaultGroundTrackPlot.DataCollectFrequency = 1;
DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
DefaultGroundTrackPlot.NumPointsToRedraw = 0;
DefaultGroundTrackPlot.ShowPlot = true;
DefaultGroundTrackPlot.MaxPlotPoints = 20000;
DefaultGroundTrackPlot.CentralBody = Earth;
DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';

Create ReportFile DefaultReportFile;
DefaultReportFile.SolverIterations = Current;
DefaultReportFile.UpperLeft = [ 0 0 ];
DefaultReportFile.Size = [ 0 0 ];
DefaultReportFile.RelativeZOrder = 0;
DefaultReportFile.Maximized = false;
DefaultReportFile.Filename = 'DefaultReportFile.txt';
DefaultReportFile.Precision = 16;
DefaultReportFile.WriteHeaders = true;
DefaultReportFile.LeftJustify = On;
DefaultReportFile.ZeroFill = Off;
DefaultReportFile.FixedWidth = true;
DefaultReportFile.Delimiter = ' ';
DefaultReportFile.ColumnWidth = 23;
DefaultReportFile.WriteReport = true;
DefaultReportFile.AppendToExistingFile = false;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate 'Shuttle to match Mir' DefaultProp(Shuttle) {Shuttle.UTCModJulian = Mir.UTCModJulian};
Propagate 'Prop Shuttle & Mir' Synchronized DefaultProp(Shuttle, Mir) {Shuttle.ElapsedSecs = 12000.0, OrbitColor = [0 255 0]};
